// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzayxolcezyqogssjssl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YXl4b2xjZXp5cW9nc3Nqc3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjkwMzIsImV4cCI6MjA2MTM0NTAzMn0.aEkUDIsW7kBv-UVJb3JwK-frCpe8tsGbQ8DKWZgVLhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);